config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  resources :settlements
  resources :transactions
  resources :accounts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'home#index'
end

app/models/settlement.rb
# frozen_string_literal: true

# Data model for a settlement. A settlement describes a financial change that results in changes to
# account balances. This is an abstract base class, all settlements are classified into types depending
# on how they tie together internal and potentially external records.
class Settlement < ApplicationRecord
  has_many :transactions
end

app/models/settlement/internal_transfer.rb
# frozen_string_literal: true

class Settlement
  # Subclass of settlement representing transfers between users. There should always be
  # two balancing Transaction records, and no external reference or value.
  class InternalTransfer < Settlement
  end
end

app/models/settlement/joining_promotion.rb
# frozen_string_literal: true

class Settlement
  # Subclass of settlement representing an initial joining promotion. This will have one
  # transaction plus a negative external amount.
  class JoiningPromotion < Settlement
  end
end

app/controllers/settlements_controller.rb
# frozen_string_literal: true

# CRUD for settlement data
class SettlementsController < ApplicationController
  before_action :set_settlement, only: %i[show edit update destroy]

  # GET /settlements or /settlements.json
  def index
    @settlements = Settlement.all
  end

  # GET /settlements/1 or /settlements/1.json
  def show; end

  # GET /settlements/new
  def new
    @settlement = Settlement.new
  end

  # GET /settlements/1/edit
  def edit; end

  # POST /settlements or /settlements.json
  def create
    @settlement = Settlement.new(settlement_params)

    respond_to do |format|
      if @settlement.save
        format.html { redirect_to settlement_url(@settlement), notice: 'Settlement was successfully created.' }
        format.json { render :show, status: :created, location: @settlement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settlements/1 or /settlements/1.json
  def update
    respond_to do |format|
      if @settlement.update(settlement_params)
        format.html { redirect_to settlement_url(@settlement), notice: 'Settlement was successfully updated.' }
        format.json { render :show, status: :ok, location: @settlement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settlements/1 or /settlements/1.json
  def destroy
    @settlement.destroy

    respond_to do |format|
      format.html { redirect_to settlements_url, notice: 'Settlement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_settlement
    @settlement = Settlement.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def settlement_params
    params.require(:settlement).permit(:type, :external_reference, :external_amount)
  end
end

app/helpers/settlements_helper.rb
# frozen_string_literal: true

# Helper methods for working with settlements
module SettlementsHelper
end

app/views/settlements/_form.html.erb
<%= form_with(model: settlement) do |form| %>
  <% if settlement.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(settlement.errors.count, "error") %> prohibited this settlement from being saved:</h2>

      <ul>
        <% settlement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_area :type %>
  </div>

  <div>
    <%= form.label :external_reference, style: "display: block" %>
    <%= form.text_area :external_reference %>
  </div>

  <div>
    <%= form.label :external_amount, style: "display: block" %>
    <%= form.number_field :external_amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/settlements/_settlement.html.erb
<div id="<%= dom_id settlement %>">
  <p>
    <strong>Type:</strong>
    <%= settlement.type %>
  </p>

  <p>
    <strong>External reference:</strong>
    <%= settlement.external_reference %>
  </p>

  <p>
    <strong>External amount:</strong>
    <%= settlement.external_amount %>
  </p>

</div>

app/views/settlements/edit.html.erb
<h1>Editing settlement</h1>

<%= render "form", settlement: @settlement %>

<br>

<div>
  <%= link_to "Show this settlement", @settlement %> |
  <%= link_to "Back to settlements", settlements_path %>
</div>

app/views/settlements/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Settlements</h1>

<div id="settlements">
  <% @settlements.each do |settlement| %>
    <%= render settlement %>
    <p>
      <%= link_to "Show this settlement", settlement %>
    </p>
  <% end %>
</div>

<%= link_to "New settlement", new_settlement_path %>

app/views/settlements/new.html.erb
<h1>New settlement</h1>

<%= render "form", settlement: @settlement %>

<br>

<div>
  <%= link_to "Back to settlements", settlements_path %>
</div>

app/views/settlements/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @settlement %>

<div>
  <%= link_to "Edit this settlement", edit_settlement_path(@settlement) %> |
  <%= link_to "Back to settlements", settlements_path %>

  <%= button_to "Destroy this settlement", @settlement, method: :delete %>
</div>